### ISSUE TITLE
Firebase Functions

### ISSUE THREAD

**Issue by Rinku8473019338** [ManuelaGar/fluttershare#2]
Did you use firebase functions?

**Comment by ManuelaGar** [comment]
Hi @Rinku8473019338, I did. As you can see in the files :)

**Comment by Rinku8473019338** [comment]
Well Hello @ManuelaGar 
Yes I can see the firebase functions
I have another issue
When I click on the image preview that is shown while getting a notification about liking or commenting in the activity feed, I receive an error that "The method '[]' was called on null.
Receiver: null
Tried calling: []("postId")"

Have you resolved this?

P.S. I am not building live push notifications, I am talking about the in-app notifications

**Comment by ManuelaGar** [comment]
I am sorry @Rinku8473019338 but I do not get such error. Can you post a picture of it?

**Comment by Rinku8473019338** [comment]
Ya sure here it is
![Screenshot (175)](https://user-images.githubusercontent.com/43800657/94169020-e4389e80-feab-11ea-93da-e7d4454cd673.png)

**Comment by Rinku8473019338** [comment]
Hey @ManuelaGar I have solved it
It is working
changed a bit of codes

**Comment by ManuelaGar** [comment]
Good to know! Happy coding :)

**Comment by Rinku8473019338** [comment]
😊😊😊
